mozilla/airmozilla

airmozilla/main/fields.py

@peterbe  I hope I have corrected the error that you mentioned.

fixes bug 1140641 - django.utils.simplejson is deprecated

---

airmozilla/manage/forms.py

I think I fixed this.
Let me know if it is okay.
Thank you.

Fix bug 1141300 - Deprecate EventFindForm

---

airmozilla/base/utils.py

@peterbe can you have a look ?

fixes Bug 1141287 - Remove _json_clean function

---

airmozilla/manage/templates/manage/dashboard.html

I believe I fixed this bug.
You can have a look and let me know if anything needs to be changed. 
Thanks.

Fix bug 1141269 - Thousands commas on Dashboard numbers

---

airmozilla/manage/forms.py
airmozilla/manage/views/users.py

I've fixed this bug. 
If anything is wrong you can let me know.

Fix bug 1141298 - Deprecate UserFindForm

---

airmozilla/base/utils.py

Bug1141288 fixing removal html to text function

---

airmozilla/manage/templates/manage/dashboard.html

Hi,
I revisited that pull request and realized I forgot to edit one line, so here is the edit of it and sorry for missing this earlier.

Fix bug 1141269 - Thousands commas on Dashboard numbers [Additional Edit]

---

airmozilla/manage/forms.py

I tried to fix this bug. If anything is wrong you can let me know.
Thank you.

fixes bug 1143826 - Remove New Location button from Event Edit Page

---

airmozilla/base/templates/500.html

Preview of Error 500 with required links, modifications and minimal design is http://swetarani.github.io/temp/error500.
Please see to it and suggest changes(if any) that we require.

Bug1124274 constructive error500 page

---

airmozilla/starred/static/starred/js/star_event.js
airmozilla/starred/templates/starred/events.html
airmozilla/starred/views.py

@peterbe serverStars were being ignored.

Fixes bug 1148566 - Concat serverStars to stars

---

airmozilla/starred/static/starred/js/starredevents.js
airmozilla/starred/templates/starred/home.html

fixes bug 1150690 - "Please wait" on Starred page when signed in

---

airmozilla/main/static/main/css/event.css
airmozilla/main/templates/main/event.html

fixes bug 1141286 List video meta data as a neat table

---

airmozilla/main/templates/main/event.html

I attempted to fix this bug. I tested it and it seems okay. @peterbe you can let me know if it is okay or it needs any changes.
Thank you.

fixes bug 1089763 - Encourage people to edit tags

---

airmozilla/main/templates/main/event.html

Umm, I tried to fix this bug. You can me know if it needs any edits.

fixes bug 1152541 - Don't show location if it is 'Pre-recorded'

---

airmozilla/manage/tests/views/test_picturegallery.py

@peterbe - Umm, how does this look like like? Any feedback on it?

fixes bug 1141306 - picture_add() lacks a lot of test coverage

---

airmozilla/main/tests/test_views.py

@peterbe - I tried to fix this bug. Let me know if it is okay or it needs any changes. Thank you.

fixes bug 1141293 - No test coverage of curated_groups_map

---

airmozilla/main/models.py
airmozilla/main/templates/main/event.html

@peterbe - I tried to fix this bug so you can check it when you get the chance.
PS. It seems something went wrong here, so I have to figure that out how to fix the issue with raven that it has.

fixes bug 1160664 - Change 'start time' notation depending on video

---

airmozilla/main/models.py
airmozilla/main/templates/main/event.html
airmozilla/main/views.py
airmozilla/manage/archiver.py
airmozilla/manage/autocompeter.py
airmozilla/manage/tests/test_archiver.py
airmozilla/manage/tests/views/test_events.py
airmozilla/manage/views/events.py
airmozilla/search/views.py

@peterbe - Does this solve "A" from here ? https://bugzilla.mozilla.org/show_bug.cgi?id=1154490 
If yes then you can tell me about "B" as you said, if no then  I am open to feedback.  I saw your wrote "OR" so do we need an "if - else" sort of thing?

fixes bug 1154490 - Need additional event status (eg. processing)

---

airmozilla/manage/templates/manage/picturegallery.html

This should resolve bug [#1170628](https://bugzilla.mozilla.org/show_bug.cgi?id=1170628).

Every 4 pictures are in a row

---

README.md

This seemed pretty easy to miss but since the wording was there I think  it might be a good idea to emphasize this text.

Emphasised need for memcached

---

airmozilla/manage/templates/manage/events.html

@peterbe - This is what I have done so far for this bug. I thought something was missing and this "Uploaded events still show as 'Pending' while they are processing."  from [bug1170869](https://bugzilla.mozilla.org/show_bug.cgi?id=1170869) meant an additional step. If anything is missing you can let me know.

fixes bug 1170869 - 'Processing' Status not quite fully implemented.

---

airmozilla/new/static/new/js/humanize-duration.js

Upgrading to HumanizeDuration 3.1.0

fixes Bug 1170186 - Upgrade to HumanizeDuration 3.0.0

---

airmozilla/popcorn/migrations/0002_auto__add_field_popcornedit_failed_attempts.py
airmozilla/popcorn/models.py
airmozilla/popcorn/static/popcorn/PopcornEditor/src/PopcornEditor.js
airmozilla/popcorn/static/popcorn/PopcornEditor/src/editor/media-gallery-editor.js
airmozilla/popcorn/static/popcorn/PopcornEditor/src/events/event.js
airmozilla/popcorn/static/popcorn/PopcornEditor/templates/basic/template.js
airmozilla/popcorn/static/popcorn/js/editor.js
airmozilla/popcorn/templates/popcorn/editor.html
airmozilla/popcorn/tests/test_views.py
airmozilla/popcorn/urls.py
airmozilla/popcorn/views.py

This updates the video editor page to now auto load the video into the editor.
This PR includes changes to popcorn-editor.js as well. To mess around the UI changes head to http://{domain}/popcorn/edit/{slug}

Editor load video

---

airmozilla/manage/vidly.py

Reverts mozilla/airmozilla#410

Revert "fixes bug 1187452 - bug in Vid.ly XML API"

---

airmozilla/base/utils.py
airmozilla/manage/tests/views/test_vidlymedia.py
airmozilla/new/sending.py
airmozilla/popcorn/cron.py
airmozilla/popcorn/renderer.py
airmozilla/popcorn/tests/test_renderer.py
airmozilla/popcorn/tests/test_views.py
airmozilla/popcorn/urls.py
airmozilla/popcorn/views.py
bin/crontab/crontab.tpl
requirements.txt

This includes:
- Code for running a cronjob which will render the first of all video submissions
- Webhook for updating our database when Vidly finishes rendering our new video
- Tests for the webhook.

Popcoder integration

---

airmozilla/popcorn/static/popcorn/js/editor.js
airmozilla/popcorn/templates/popcorn/editor.html
airmozilla/popcorn/tests/test_views.py
airmozilla/popcorn/urls.py
airmozilla/popcorn/views.py

Hooked up save button for creating PopcornEdit

---

airmozilla/main/tests/selenium/test_calendar.py
bin/travis/setup.sh
requirements.txt

Bug-1186669 Re-enable selenium tests

---

airmozilla/popcorn/renderer.py
airmozilla/popcorn/tests/test_renderer.py

fixes bug 1194855 - Resubmit video edits in on-HD if necessary

---

.travis.yml
airmozilla/base/static/js/base.js
airmozilla/base/templates/404.html
airmozilla/main/context_processors.py
airmozilla/main/static/main/css/main.css
airmozilla/main/static/main/js/es_trigger.js
airmozilla/main/static/main/js/related-content.js
airmozilla/main/templates/main/_sidebar_inner.html
airmozilla/main/templates/main/channels.html
airmozilla/main/templates/main/es.html
airmozilla/main/templates/main/event.html
airmozilla/main/templates/main/home.html
airmozilla/main/templates/main/main_base.html
airmozilla/main/tests/views/test_pages.py
airmozilla/main/tests/views/test_related.py
airmozilla/main/urls.py
airmozilla/main/views.py
airmozilla/manage/cron.py
airmozilla/manage/related.py
airmozilla/search/static/search/css/search.css
airmozilla/search/templates/search/home.html
airmozilla/settings/base.py
airmozilla/settings/settings_test.py
bin/crontab/crontab.tpl
requirements.txt
settings_test.py

@peterbe - This is not functional right now. I'll remove the prints from it later on and we said the html suppose to be on event.html, opposed to it being a new file as I did, but I didn't really do that. I'ld like to have some feedback on this on if it is going towards the right direction or it is totally off. Thank you :)

Bug 981128 - Also in channel or Related events

---

airmozilla/main/templates/main/event.html

@peterbe - I attempted to fix this bug if there is a need for any changes feel free to let me know :)

fixes bug 1203669 - Drop time-stamp from Chapter display.

---

airmozilla/base/utils.py
airmozilla/manage/helpers.py
airmozilla/manage/related.py
airmozilla/manage/views/events.py
airmozilla/manage/views/utils.py
airmozilla/search/utils.py

This change is for consolidating the STOPWORDS list according to the 1201143 bug tracker.

Changes to fix the Bug 1201143

---

airmozilla/settings/base.py

adding julian.alexander.murillo to contributors
